import React from 'react';
import { 
  FileText, 
  Printer, 
  Download, 
  Share2, 
  ShieldCheck, 
  CheckCircle2, 
  AlertTriangle, 
  XCircle, 
  ArrowLeft,
  Calendar,
  UserCheck,
  Building,
  Award
} from 'lucide-react';
import { Link } from 'react-router-dom';
import { ResponsiveContainer, PieChart, Pie, Cell, Tooltip } from 'recharts';
import { InspectionStepper } from '../components/common/InspectionStepper';
import { getActiveInspection } from '../services/inspectionStore';
import { getDynamicComplianceRules } from '../services/genericExtractor';

export const ComplianceReportPage: React.FC = () => {
  const activeInspection = getActiveInspection();
  const complianceRules = React.useMemo(() => getDynamicComplianceRules(activeInspection), [activeInspection]);

  const passedCount = complianceRules.filter(r => r.status === 'passed').length;
  const warningCount = complianceRules.filter(r => r.status === 'warning').length;
  const failedCount = complianceRules.filter(r => r.status === 'failed').length;

  const chartData = [
    { name: 'Passed Rules', value: passedCount + 8, color: '#10b981' },
    { name: 'Warnings', value: warningCount, color: '#f59e0b' },
    { name: 'Violations', value: failedCount, color: '#ef4444' },
  ];

  const handlePrint = () => {
    window.print();
  };

  const handleDownloadPDF = () => {
    alert("Simulating PDF generation for Inspection Certificate: " + activeInspection.id);
  };

  return (
    <div className="space-y-6 animate-fade-in">
      <InspectionStepper />

      {/* Header Actions */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 pb-2">
        <div>
          <div className="flex items-center gap-2 mb-1">
            <span className="text-xs font-mono font-semibold text-blue-600 bg-blue-50 px-2 py-0.5 rounded">
              {activeInspection.id}
            </span>
            <span className="text-xs text-slate-400">• Step 8 of 8</span>
          </div>
          <h1 className="text-2xl font-bold text-slate-900 tracking-tight">Packaged Product Compliance Report</h1>
          <p className="text-xs sm:text-sm text-slate-500">
            Official statutory audit certificate generated by ReguCheck AI Compliance Rule Engine.
          </p>
        </div>

        <div className="flex items-center gap-2">
          <button
            onClick={handlePrint}
            className="px-3.5 py-2 bg-white hover:bg-slate-50 text-slate-700 border border-slate-200 rounded-xl text-xs font-semibold shadow-subtle flex items-center gap-1.5 transition"
          >
            <Printer className="w-3.5 h-3.5" />
            <span>Print Report</span>
          </button>

          <button
            onClick={handleDownloadPDF}
            className="px-4 py-2 bg-blue-600 hover:bg-blue-700 text-white rounded-xl text-xs font-semibold shadow-md shadow-blue-500/20 flex items-center gap-1.5 transition"
          >
            <Download className="w-3.5 h-3.5" />
            <span>Download Audit PDF</span>
          </button>
        </div>
      </div>

      {/* Certificate / Report Document Card */}
      <div className="bg-white rounded-2xl border border-slate-200 shadow-card overflow-hidden">
        {/* Document Top Header Banner */}
        <div className="p-6 sm:p-8 bg-gradient-to-r from-navy-950 to-navy-900 text-white flex flex-col md:flex-row items-start md:items-center justify-between gap-6 border-b border-navy-800">
          <div className="flex items-center gap-4">
            <div className="w-14 h-14 rounded-2xl bg-blue-600 flex items-center justify-center text-white shadow-lg">
              <Award className="w-8 h-8" />
            </div>
            <div>
              <div className="flex items-center gap-2">
                <span className="font-extrabold text-xl tracking-tight">ReguCheck AI</span>
                <span className="text-[10px] px-2 py-0.5 rounded bg-blue-500/20 text-blue-300 border border-blue-400/30">
                  STATUTORY AUDIT CERTIFICATE
                </span>
              </div>
              <h2 className="text-lg font-bold text-slate-100 mt-1">{activeInspection.product_name}</h2>
              <p className="text-xs text-slate-400">Brand: {activeInspection.brand} • Package: {activeInspection.package_type}</p>
            </div>
          </div>

          {/* Overall Compliance Verdict Tag */}
          <div className="bg-white/10 backdrop-blur rounded-xl p-3 border border-white/10 text-right self-stretch md:self-auto flex md:flex-col justify-between items-center md:items-end">
            <span className="text-[11px] text-slate-300 font-medium">Compliance Verdict:</span>
            <span className="text-base font-extrabold text-amber-400 mt-0.5">
              Conditional Approval ({activeInspection.compliance_score}/100)
            </span>
          </div>
        </div>

        {/* Product & Audit Metadata Grid */}
        <div className="grid grid-cols-2 sm:grid-cols-4 gap-4 p-6 bg-slate-50/70 border-b border-slate-200 text-xs">
          <div>
            <span className="text-slate-400 block mb-0.5">Inspection Reference:</span>
            <p className="font-mono font-bold text-slate-900">{activeInspection.id}</p>
          </div>
          <div>
            <span className="text-slate-400 block mb-0.5">Audit Timestamp:</span>
            <p className="font-medium text-slate-800">{activeInspection.inspection_date}</p>
          </div>
          <div>
            <span className="text-slate-400 block mb-0.5">Auditing Specialist:</span>
            <p className="font-medium text-slate-800">{activeInspection.inspector_name}</p>
          </div>
          <div>
            <span className="text-slate-400 block mb-0.5">Statutory Frameworks:</span>
            <p className="font-medium text-slate-800 truncate">{activeInspection.jurisdiction}</p>
          </div>
        </div>

        {/* Body Section: Chart & Summary */}
        <div className="p-6 sm:p-8 space-y-8">
          <div className="grid grid-cols-1 md:grid-cols-12 gap-6 items-center">
            {/* Visual Donut Chart (4 cols) */}
            <div className="md:col-span-4 bg-slate-50 rounded-xl p-4 border border-slate-200 flex flex-col items-center justify-center">
              <h4 className="text-xs font-bold text-slate-700 mb-2">Rule Evaluation Distribution</h4>
              <div className="w-36 h-36">
                <ResponsiveContainer width="100%" height="100%">
                  <PieChart>
                    <Pie
                      data={chartData}
                      cx="50%"
                      cy="50%"
                      innerRadius={36}
                      outerRadius={56}
                      paddingAngle={4}
                      dataKey="value"
                    >
                      {chartData.map((entry, index) => (
                        <Cell key={`cell-${index}`} fill={entry.color} />
                      ))}
                    </Pie>
                    <Tooltip contentStyle={{ fontSize: '11px', borderRadius: '6px' }} />
                  </PieChart>
                </ResponsiveContainer>
              </div>
              <div className="flex items-center gap-3 text-[11px] mt-2">
                <span className="flex items-center gap-1 text-emerald-700 font-semibold">
                  <span className="w-2 h-2 rounded-full bg-emerald-500"></span> 14 Passed
                </span>
                <span className="flex items-center gap-1 text-amber-700 font-semibold">
                  <span className="w-2 h-2 rounded-full bg-amber-500"></span> 2 Warnings
                </span>
                <span className="flex items-center gap-1 text-rose-700 font-semibold">
                  <span className="w-2 h-2 rounded-full bg-rose-500"></span> 2 Failed
                </span>
              </div>
            </div>

            {/* Executive Summary Statement (8 cols) */}
            <div className="md:col-span-8 space-y-3 text-xs text-slate-600 leading-relaxed">
              <h3 className="text-sm font-bold text-slate-900">Executive Audit Summary</h3>
              <p>
                The packaged product label for <strong>{activeInspection.product_name}</strong> was 
                evaluated against statutory provisions of the <em>FSSAI (Labelling & Display) Regulations 2020</em> and 
                the <em>Legal Metrology (Packaged Commodities) Rules 2011</em>.
              </p>
              <div className="p-3.5 rounded-xl bg-amber-50 border border-amber-200 text-amber-900 space-y-1">
                <p className="font-semibold text-xs">Required Remediation Prior to Commercial Printing:</p>
                <ul className="list-disc list-inside text-[11px] space-y-0.5 text-amber-800">
                  <li><strong>RULE-LM-009:</strong> Verify Net Quantity '{activeInspection.declared_net_weight || "declared unit"}' numeral height satisfies ≥ 4.0mm requirement.</li>
                  <li><strong>RULE-FS-055:</strong> Add official FSSAI Vegetarian green dot in green square logo.</li>
                  <li><strong>RULE-FS-052:</strong> Ensure mandatory declarations use bold contrasting font.</li>
                </ul>
              </div>
            </div>
          </div>

          {/* Full Audit Checklist Table */}
          <div className="space-y-3">
            <h3 className="text-sm font-bold text-slate-900">Full Statutory Evaluation Checklist</h3>
            <div className="border border-slate-200 rounded-xl overflow-hidden">
              <table className="w-full text-left text-xs">
                <thead>
                  <tr className="bg-slate-50 border-b border-slate-200 text-[11px] font-bold text-slate-500 uppercase tracking-wider">
                    <th className="py-2.5 px-4">Rule ID & Source</th>
                    <th className="py-2.5 px-4">Requirement</th>
                    <th className="py-2.5 px-4">Detected Value</th>
                    <th className="py-2.5 px-4 text-right">Evaluation</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-slate-100">
                  {complianceRules.map((rule) => (
                    <tr key={rule.rule_id} className="hover:bg-slate-50/60">
                      <td className="py-3 px-4 font-mono font-semibold text-slate-800">
                        {rule.rule_id}
                        <span className="block text-[10px] text-slate-400 font-normal">{rule.category}</span>
                      </td>
                      <td className="py-3 px-4 text-slate-700 max-w-xs">{rule.title}</td>
                      <td className="py-3 px-4 text-slate-500 font-mono text-[11px]">{rule.found_text}</td>
                      <td className="py-3 px-4 text-right">
                        <span className={`inline-flex items-center gap-1 px-2.5 py-0.5 rounded-full text-[10px] font-bold uppercase tracking-wider ${
                          rule.status === 'passed'
                            ? 'bg-emerald-50 text-emerald-700 border border-emerald-200'
                            : rule.status === 'warning'
                            ? 'bg-amber-50 text-amber-700 border border-amber-200'
                            : 'bg-rose-50 text-rose-700 border border-rose-200'
                        }`}>
                          {rule.status}
                        </span>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </div>

          {/* Sign-off & Authority Block */}
          <div className="pt-6 border-t border-slate-200 flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4 text-xs">
            <div className="flex items-center gap-3">
              <div className="w-10 h-10 rounded-full bg-slate-100 flex items-center justify-center font-bold text-slate-700">
                TM
              </div>
              <div>
                <p className="font-bold text-slate-900">{activeInspection.inspector_name}</p>
                <p className="text-[11px] text-slate-400">Lead Regulatory Affairs & Quality Specialist</p>
              </div>
            </div>

            <div className="text-right text-[11px] text-slate-400">
              <p>Generated automatically via ReguCheck AI Engine</p>
              <p className="font-mono">Security Hash: 9f88c3a01-2026-FSSAI</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};
