import React, { useState } from 'react';
import { Link } from 'react-router-dom';
import { 
  FileCode, 
  Copy, 
  Check, 
  ArrowRight, 
  Cpu, 
  Search, 
  Sparkles, 
  CheckCircle2,
  Filter,
  Eye
} from 'lucide-react';
import { InspectionStepper } from '../components/common/InspectionStepper';
import { MOCK_OCR_BLOCKS, CURRENT_INSPECTION } from '../data/mockData';

export const OCRResultsPage: React.FC = () => {
  const [selectedBlockId, setSelectedBlockId] = useState<string | null>(null);
  const [copied, setCopied] = useState(false);
  const [searchTerm, setSearchTerm] = useState('');
  const [viewMode, setViewMode] = useState<'blocks' | 'raw'>('blocks');

  const filteredBlocks = MOCK_OCR_BLOCKS.filter(b => 
    b.text.toLowerCase().includes(searchTerm.toLowerCase())
  );

  const rawTextContent = MOCK_OCR_BLOCKS.map(b => b.text).join('\n');

  const handleCopyRaw = () => {
    navigator.clipboard.writeText(rawTextContent);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="space-y-6 animate-fade-in">
      <InspectionStepper />

      {/* Page Title & Reminder Banner */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-2">
        <div>
          <h1 className="text-2xl font-bold text-slate-900 tracking-tight">Step 3: OCR Results & Text Recognition</h1>
          <p className="text-xs sm:text-sm text-slate-500">
            Detected text blocks, character bounding coordinates, and confidence levels generated by the OCR Service.
          </p>
        </div>

        <div className="flex items-center gap-2">
          <Link
            to="/inspect/detected-info"
            className="px-4 py-2 bg-blue-600 hover:bg-blue-700 text-white text-xs font-semibold rounded-xl shadow-md shadow-blue-500/20 flex items-center gap-1.5 transition"
          >
            <span>Step 4: Detected Info</span>
            <ArrowRight className="w-3.5 h-3.5" />
          </Link>
        </div>
      </div>

      {/* Teammate OCR Pluggable Architecture Note */}
      <div className="p-4 rounded-xl bg-amber-50 border border-amber-200 text-amber-900 flex items-start gap-3 text-xs">
        <Cpu className="w-5 h-5 text-amber-600 shrink-0 mt-0.5" />
        <div>
          <span className="font-bold">OCR Abstraction Layer Notice:</span> Currently powered by{' '}
          <code className="bg-amber-100 px-1 py-0.5 rounded font-mono text-[11px]">MockOCRService</code>. 
          When your teammate finishes developing the OCR model, it will plug seamlessly into{' '}
          <code className="bg-amber-100 px-1 py-0.5 rounded font-mono text-[11px]">backend/app/services/ocr/base.py</code>{' '}
          without modifying any frontend pages.
        </div>
      </div>

      {/* Main Content Layout */}
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-6">
        {/* Left: Interactive Label with Bounding Box Overlay (5 cols) */}
        <div className="lg:col-span-5 bg-white rounded-2xl border border-slate-200/80 p-5 shadow-subtle flex flex-col justify-between">
          <div>
            <div className="flex items-center justify-between pb-3 border-b border-slate-100 mb-3">
              <h3 className="font-bold text-sm text-slate-900 flex items-center gap-2">
                <Eye className="w-4 h-4 text-blue-600" />
                <span>Interactive Label Bounding Map</span>
              </h3>
              <span className="text-[10px] text-slate-400">Click a box to inspect</span>
            </div>

            <div className="relative rounded-xl overflow-hidden border border-slate-300 bg-slate-900 aspect-[3/4] flex items-center justify-center">
              <img 
                src={CURRENT_INSPECTION.image_url} 
                alt="Product Label" 
                className="w-full h-full object-cover opacity-85"
              />

              {/* Interactive Bounding Boxes */}
              {MOCK_OCR_BLOCKS.map((block) => {
                const isSelected = selectedBlockId === block.id;
                return (
                  <div
                    key={block.id}
                    onClick={() => setSelectedBlockId(block.id)}
                    style={{
                      left: `${block.box.x}%`,
                      top: `${block.box.y}%`,
                      width: `${block.box.width}%`,
                      height: `${block.box.height}%`,
                    }}
                    className={`absolute border-2 cursor-pointer transition-all duration-150 flex items-start p-0.5 ${
                      isSelected
                        ? 'border-yellow-400 bg-yellow-400/30 z-20 shadow-md ring-2 ring-yellow-300'
                        : block.category === 'legal'
                        ? 'border-blue-400 bg-blue-500/10 hover:bg-blue-500/30'
                        : block.category === 'ingredient'
                        ? 'border-purple-400 bg-purple-500/10 hover:bg-purple-500/30'
                        : 'border-emerald-400 bg-emerald-500/10 hover:bg-emerald-500/30'
                    }`}
                  >
                    <span className="text-[8px] bg-slate-900/90 text-white font-mono px-1 rounded truncate pointer-events-none">
                      {Math.round(block.confidence * 100)}%
                    </span>
                  </div>
                );
              })}
            </div>
          </div>

          <div className="mt-4 pt-3 border-t border-slate-100 flex items-center justify-between text-xs text-slate-500">
            <span>Selected Block: <strong className="text-slate-800">{selectedBlockId || 'None (Click a box)'}</strong></span>
            <button 
              onClick={() => setSelectedBlockId(null)}
              className="text-blue-600 hover:underline text-[11px]"
            >
              Clear Selection
            </button>
          </div>
        </div>

        {/* Right: OCR Detected Blocks & Raw Stream (7 cols) */}
        <div className="lg:col-span-7 bg-white rounded-2xl border border-slate-200/80 p-5 shadow-subtle flex flex-col justify-between space-y-4">
          {/* Controls Header */}
          <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 pb-3 border-b border-slate-100">
            <div className="flex items-center gap-2">
              <div className="bg-slate-100 p-1 rounded-lg flex text-xs">
                <button
                  onClick={() => setViewMode('blocks')}
                  className={`px-3 py-1 rounded-md font-medium transition ${
                    viewMode === 'blocks' ? 'bg-white text-slate-900 shadow-subtle' : 'text-slate-500'
                  }`}
                >
                  Block Inspector ({MOCK_OCR_BLOCKS.length})
                </button>
                <button
                  onClick={() => setViewMode('raw')}
                  className={`px-3 py-1 rounded-md font-medium transition ${
                    viewMode === 'raw' ? 'bg-white text-slate-900 shadow-subtle' : 'text-slate-500'
                  }`}
                >
                  Raw OCR Stream
                </button>
              </div>
            </div>

            <div className="flex items-center gap-2">
              <div className="relative">
                <Search className="w-3.5 h-3.5 text-slate-400 absolute left-2.5 top-1/2 -translate-y-1/2" />
                <input
                  type="text"
                  placeholder="Filter text..."
                  value={searchTerm}
                  onChange={(e) => setSearchTerm(e.target.value)}
                  className="pl-8 pr-3 py-1 text-xs bg-slate-50 border border-slate-200 rounded-lg focus:outline-none focus:ring-1 focus:ring-blue-500 text-slate-800"
                />
              </div>

              <button
                onClick={handleCopyRaw}
                className="px-3 py-1 bg-slate-100 hover:bg-slate-200 text-slate-700 text-xs font-semibold rounded-lg flex items-center gap-1 transition"
                title="Copy all raw text"
              >
                {copied ? <Check className="w-3.5 h-3.5 text-emerald-600" /> : <Copy className="w-3.5 h-3.5" />}
                <span>{copied ? 'Copied' : 'Copy'}</span>
              </button>
            </div>
          </div>

          {/* View Mode 1: Structured Blocks */}
          {viewMode === 'blocks' ? (
            <div className="space-y-2.5 max-h-[460px] overflow-y-auto pr-1">
              {filteredBlocks.map((block) => {
                const isSelected = selectedBlockId === block.id;
                return (
                  <div
                    key={block.id}
                    onClick={() => setSelectedBlockId(block.id)}
                    className={`p-3 rounded-xl border text-xs cursor-pointer transition ${
                      isSelected
                        ? 'border-blue-500 bg-blue-50/60 ring-1 ring-blue-500 shadow-subtle'
                        : 'border-slate-200/80 bg-slate-50/60 hover:bg-slate-100/80'
                    }`}
                  >
                    <div className="flex items-center justify-between mb-1.5">
                      <div className="flex items-center gap-2">
                        <span className="font-mono font-bold text-[10px] text-slate-500">[{block.id}]</span>
                        <span className={`px-2 py-0.2 rounded text-[10px] font-semibold uppercase tracking-wider ${
                          block.category === 'legal'
                            ? 'bg-blue-100 text-blue-800'
                            : block.category === 'ingredient'
                            ? 'bg-purple-100 text-purple-800'
                            : block.category === 'nutrition'
                            ? 'bg-amber-100 text-amber-800'
                            : 'bg-slate-200 text-slate-700'
                        }`}>
                          {block.category || 'general'}
                        </span>
                      </div>
                      <span className="text-[11px] font-medium text-emerald-600 font-mono">
                        {Math.round(block.confidence * 100)}% match
                      </span>
                    </div>
                    <p className="font-mono text-slate-800 leading-relaxed">{block.text}</p>
                  </div>
                );
              })}
            </div>
          ) : (
            /* View Mode 2: Raw Monospace Text */
            <div className="bg-slate-950 text-slate-100 p-4 rounded-xl font-mono text-xs leading-relaxed max-h-[460px] overflow-y-auto border border-slate-800">
              <pre className="whitespace-pre-wrap">{rawTextContent}</pre>
            </div>
          )}

          {/* Bottom Action Footer */}
          <div className="pt-3 border-t border-slate-100 flex items-center justify-between">
            <span className="text-xs text-slate-500">
              {filteredBlocks.length} text blocks ready for entity extraction
            </span>
            <Link
              to="/inspect/detected-info"
              className="px-5 py-2 bg-blue-600 hover:bg-blue-700 text-white font-semibold text-xs rounded-xl shadow-md shadow-blue-500/20 flex items-center gap-2 transition"
            >
              <span>Next: View Detected Information</span>
              <ArrowRight className="w-4 h-4" />
            </Link>
          </div>
        </div>
      </div>
    </div>
  );
};
